/* eslint-disable */
export default {
  "mindmap": [
    {
      "type": "excel",
      "key": "excel",
      "name": "Excel",
      "desc": "Excel",
      "resolver": "excel",
      "order": 10,
      "logo": "excel",
      "category": "doc",
      "index": "name[R],id",
      "count": "1,2",
      "suffix": ".xlsx,.xls",
      "keywords": "excel",
      "accept": "application/vnd*",
      "mc_status": "none"
    },
    {
      "type": "word",
      "key": "word",
      "name": "Word",
      "desc": "Word",
      "resolver": "word",
      "order": 9,
      "logo": "word",
      "category": "doc",
      "suffix": ".docx,.doc",
      "keywords": "word",
      "mc_status": "none"
    },
    {
      "type": "ppt",
      "key": "ppt",
      "name": "PPT",
      "desc": "PPT",
      "resolver": "ppt",
      "order": 11,
      "logo": "ppt",
      "category": "doc",
      "suffix": ".pptx,.ppt",
      "keywords": "ppt",
      "mc_status": "none",
      "status": "disabled"
    },
    {
      "type": "txt",
      "key": "txt",
      "name": "TXT",
      "desc": "TXT",
      "resolver": "txt",
      "order": 2,
      "logo": "txt",
      "category": "doc",
      "suffix": ".txt",
      "keywords": "txt",
      "mc_status": "none"
    },
    {
      "type": "pdf",
      "key": "pdf",
      "name": "PDF",
      "desc": "PDF",
      "resolver": "pdf",
      "order": 16,
      "logo": "pdf",
      "category": "doc",
      "suffix": ".pdf",
      "keywords": "pdf",
      "mc_status": "none"
    },
    {
      "type": "csv",
      "key": "csv",
      "name": "CSV",
      "desc": "CSV",
      "resolver": "csv",
      "order": 17,
      "logo": "csv",
      "category": "doc",
      "index": "name[R],id",
      "count": "2",
      "suffix": ".csv",
      "keywords": "csv",
      "accept": "text/csv",
      "mc_status": "ready"
    },
    {
      "type": "json",
      "key": "json",
      "name": "JSON",
      "desc": "JSON",
      "resolver": "json",
      "order": 1,
      "logo": "json",
      "category": "doc",
      "index": "id",
      "count": "1,2",
      "suffix": ".json",
      "keywords": "json",
      "accept": "application/json",
      "mc_status": "ready"
    },
    {
      "type": "markdown",
      "key": "markdown",
      "name": "Markdown",
      "desc": "Markdown",
      "resolver": "markdown",
      "order": 0,
      "logo": "markdown",
      "category": "doc",
      "suffix": ".md",
      "keywords": "markdown",
      "pipe": "file,text",
      "mc_status": "ready"
    },
    {
      "type": "nrd",
      "key": "nrd",
      "name": "NRD Studio",
      "desc": "NRD Studio",
      "resolver": "nrd",
      "order": 4,
      "logo": "nrdstudio",
      "category": "product",
      "suffix": ".nrd",
      "keywords": "nrd",
      "mc_status": "ready"
    },
    {
      "type": "xmind",
      "key": "xmind",
      "name": "Xmind",
      "desc": "Xmind",
      "resolver": "xmind",
      "order": 3,
      "logo": "xmind",
      "category": "product",
      "suffix": ".xmind",
      "keywords": "xmind",
      "mc_status": "ready"
    },
    {
      "type": "processon",
      "key": "processon",
      "name": "Processon",
      "desc": "Processon",
      "resolver": "processon",
      "order": 5,
      "logo": "processon",
      "category": "product",
      "suffix": ".pos",
      "keywords": "processon",
      "mc_status": "ready"
    },
    {
      "type": "gitmind",
      "key": "gitmind",
      "name": "Gitmind",
      "desc": "Gitmind",
      "resolver": "gitmind",
      "order": 7,
      "logo": "gitmind",
      "category": "product",
      "suffix": ".gmind",
      "keywords": "gitmind",
      "mc_status": "ready"
    },
    {
      "type": "mubu",
      "key": "mubu",
      "name": "幕布",
      "desc": "幕布",
      "resolver": "mubu",
      "order": 6,
      "logo": "mubu",
      "category": "product",
      "subtype": "freemind,opml",
      "suffix": ".mm,.opml",
      "keywords": "mubu"
    },
    {
      "type": "freemind",
      "key": "freemind",
      "name": "Freemind",
      "desc": "Freemind",
      "resolver": "freemind",
      "order": 8,
      "logo": "freemind",
      "category": "product",
      "suffix": ".mm",
      "keywords": "freemind",
      "mc_status": "ready"
    },
    {
      "type": "mindnode",
      "key": "mindnode",
      "name": "MindNode",
      "desc": "MindNode",
      "resolver": "mindnode",
      "order": 12,
      "logo": "mindnode",
      "category": "product",
      "subtype": "freemind,opml",
      "suffix": ".mm,.opml",
      "keywords": "mindnode"
    },
    {
      "type": "kityminder",
      "key": "kityminder",
      "name": "百度脑图",
      "desc": "百度脑图",
      "resolver": "kityminder",
      "order": 14,
      "logo": "kityminder",
      "category": "product",
      "suffix": ".km,.mm",
      "keywords": "kityminder"
    },
    {
      "type": "jsmind",
      "key": "jsmind",
      "name": "jsMind",
      "desc": "jsMind",
      "resolver": "jsmind",
      "order": 18,
      "logo": "jsmind",
      "category": "product",
      "suffix": ".jm",
      "keywords": "jsmind",
      "mc_status": "ready"
    },
    {
      "type": "yinxiang",
      "key": "yinxiang",
      "name": "印象笔记",
      "desc": "印象笔记",
      "resolver": "yinxiang",
      "order": 19,
      "logo": "yinxiang",
      "category": "product",
      "suffix": ".evermind",
      "keywords": "yinxiang",
      "mc_status": "ready"
    },
    {
      "type": "xunjie",
      "key": "xunjie",
      "name": "迅捷画图",
      "desc": "迅捷画图",
      "resolver": "xunjie",
      "order": 20,
      "logo": "xunjie",
      "category": "product",
      "suffix": ".json",
      "keywords": "xunjie",
      "accept": "application/json"
    },
    {
      "type": "treemind",
      "key": "treemind",
      "name": "TreeMind",
      "desc": "树图",
      "resolver": "treemind",
      "order": 21,
      "logo": "treemind",
      "category": "product",
      "suffix": ".tm",
      "keywords": "treemind",
      "mc_status": "ready"
    },
    {
      "type": "zhixi",
      "key": "zhixi",
      "name": "知犀",
      "desc": "知犀",
      "resolver": "zhixi",
      "order": 22,
      "logo": "zhixi",
      "category": "product",
      "suffix": ".zxm",
      "keywords": "zhixi",
      "mc_status": "ready"
    },
    {
      "type": "mindmaster",
      "key": "mindmaster",
      "name": "MindMaster",
      "desc": "MindMaster",
      "resolver": "mindmaster",
      "order": 13,
      "logo": "mindmaster",
      "category": "product",
      "subtype": "freemind,opml",
      "suffix": ".mmap",
      "keywords": "mindmaster"
    },
    {
      "type": "opml",
      "key": "opml",
      "name": "OPML",
      "desc": "OPML",
      "resolver": "opml",
      "order": 15,
      "logo": "opml",
      "category": "doc",
      "suffix": ".opml",
      "keywords": "opml",
      "pipe": "file,text",
      "mc_status": "ready"
    },
    {
      "type": "mindline",
      "key": "mindline",
      "name": "MindLine",
      "desc": "MindLine",
      "resolver": "mindline",
      "order": 23,
      "logo": "mindline",
      "category": "product",
      "suffix": ".mm",
      "keywords": "mindline"
    },
    {
      "type": "mindmanager",
      "key": "mindmanager",
      "name": "MindManager",
      "desc": "MindManager",
      "resolver": "mindmanager",
      "order": 24,
      "logo": "mindmanager",
      "category": "product",
      "subtype": "freemind,opml",
      "suffix": ".mmap",
      "keywords": "mindmanager",
      "mc_status": "ready"
    },
    {
      "type": "jpg",
      "key": "jpg",
      "name": "JPG",
      "desc": "JPG",
      "resolver": "jpg",
      "order": 25,
      "logo": "jpg",
      "category": "image",
      "suffix": ".jpg,.jpeg",
      "keywords": "jpg,jpeg",
      "mc_status": "none"
    },
    {
      "type": "png",
      "key": "png",
      "name": "PNG",
      "desc": "PNG",
      "resolver": "png",
      "order": 26,
      "logo": "png",
      "category": "image",
      "suffix": ".png",
      "keywords": "png",
      "mc_status": "none"
    },
    {
      "type": "webp",
      "key": "webp",
      "name": "WEBP",
      "desc": "WEBP",
      "resolver": "webp",
      "order": 27,
      "logo": "webp",
      "category": "image",
      "suffix": ".webp",
      "keywords": "webp",
      "mc_status": "none",
      "status": "disabled"
    },
    {
      "type": "ico",
      "key": "ico",
      "name": "ICO",
      "desc": "ICO",
      "resolver": "ico",
      "order": 28,
      "logo": "ico",
      "category": "image",
      "suffix": ".ico",
      "keywords": "ico",
      "mc_status": "none",
      "status": "disabled"
    },
    {
      "type": "gif",
      "key": "gif",
      "name": "GIF",
      "desc": "GIF",
      "resolver": "gif",
      "order": 29,
      "logo": "gif",
      "category": "image",
      "suffix": ".gif",
      "keywords": "gif",
      "mc_status": "none",
      "status": "disabled"
    },
    {
      "type": "svg",
      "key": "svg",
      "name": "SVG",
      "desc": "SVG",
      "resolver": "svg",
      "order": 30,
      "logo": "svg",
      "category": "image",
      "suffix": ".svg",
      "keywords": "svg",
      "mc_status": "none",
      "status": "disabled"
    },
    {
      "type": "nrd_2d",
      "key": "nrd_2d",
      "name": "2D图谱",
      "desc": "2D图谱",
      "resolver": "nrd_2d",
      "order": 31,
      "logo": "nrd_2d",
      "category": "kg",
      "suffix": ".nrd",
      "keywords": "nrd_2d"
    },
    {
      "type": "nrd_3d",
      "key": "nrd_3d",
      "name": "3D图谱",
      "desc": "3D图谱",
      "resolver": "nrd_3d",
      "order": 32,
      "logo": "nrd_3d",
      "category": "kg",
      "suffix": ".nrd",
      "keywords": "nrd_3d"
    },
    {
      "type": "nrd_mn",
      "key": "nrd_mn",
      "name": "思维笔记",
      "desc": "思维笔记",
      "resolver": "nrd_mn",
      "order": 33,
      "logo": "nrd_mn",
      "category": "product",
      "suffix": ".nrd",
      "keywords": "nrd_mn",
      "status": "disabled"
    },
    {
      "type": "rtf",
      "status": "disabled"
    },
    {
      "type": "textbundle",
      "name": "TextBundle ",
      "status": "disabled"
    },
    {
      "type": "TextPack",
      "status": "disabled"
    }
  ],
  "auto": [
    {
      "id": 1,
      "type": "excel",
      "key": "excel",
      "name": "EXCEL",
      "handle": "excel",
      "order": 0,
      "logo": "excel",
      "mindmap": 0,
      "mindnote": 0,
      "index": "name[R],id",
      "suffix": ".xlsx,.xls",
      "status": "disabled"
    },
    {
      "id": 2,
      "type": "csv",
      "key": "csv",
      "name": "CSV",
      "handle": "csv",
      "order": 1,
      "logo": "csv",
      "mindmap": 0,
      "mindnote": 0,
      "index": "name[R],id",
      "suffix": ".csv"
    },
    {
      "id": 3,
      "type": "json",
      "key": "json",
      "name": "JSON",
      "handle": "json",
      "order": 2,
      "logo": "json",
      "mindmap": 0,
      "mindnote": 0,
      "index": "id",
      "suffix": ".json"
    },
    {
      "id": 4,
      "type": "markdown",
      "key": "markdown",
      "name": "Markdown",
      "handle": "markdown",
      "order": 3,
      "logo": "markdown",
      "suffix": ".md"
    },
    {
      "id": 5,
      "type": "nrd",
      "key": "nrd",
      "name": "NRD Studio",
      "handle": "nrd",
      "order": 4,
      "logo": "nrdstudio",
      "suffix": ".nrd"
    },
    {
      "id": 6,
      "type": "freemind",
      "key": "freemind",
      "name": "FreeMind",
      "handle": "freemind",
      "order": 5,
      "logo": "freemind",
      "suffix": ".mm"
    },
    {
      "id": 7,
      "type": "opml",
      "key": "opml",
      "name": "OPML",
      "handle": "opml",
      "order": 6,
      "logo": "opml",
      "suffix": ".opml"
    },
    {
      "id": 8,
      "type": "xmind",
      "key": "xmind",
      "name": "Xmind",
      "handle": "xmind",
      "order": 7,
      "logo": "xmind",
      "suffix": ".xmind"
    },
    {
      "id": 9,
      "type": "processon",
      "key": "processon",
      "name": "Processon",
      "handle": "processon",
      "order": 8,
      "logo": "processon",
      "suffix": ".pos"
    },
    {
      "id": 10,
      "type": "gitmind",
      "key": "gitmind",
      "name": "GitMind",
      "handle": "gitmind",
      "order": 9,
      "logo": "gitmind",
      "suffix": ".gmind"
    },
    {
      "type": "mmap",
      "key": "mmap",
      "name": "MindManager",
      "handle": "mmap",
      "order": 10,
      "logo": "mmap",
      "suffix": ".mmap"
    }
  ]
}